### ISSUE TITLE
about the preprocessing

### ISSUE THREAD

**Issue by REDXXXX** [yongqyu/STRNN#4]
Thank you for the implemention of ST-RNN.I have get some questions about the code.
1. How do you choose value for the time unper bound of low bound ? And the dst unper bound and low bound.
2. given a user's trajectory ,how could you handle the trajectory and make each check_in ( user, lat,lng, time-stamp) into user-td,user-ld,user-loc,user-dst.
![image](https://user-images.githubusercontent.com/22863632/50154800-62ded000-0305-11e9-9ae8-45592645fee5.png)

3. I want to know how the loc_len is calculated.For example,if the window width is  6h,and three check-in is within 6 h,such as A ,B,C, then A 's loc_len is 1, B's loc_len is 2, C's loc_len is 3?

I would appreciate it a lot if you could help me.Best wishes to you.Cause I have to know the answers to preprocess my

**Comment by REDXXXX** [comment]
I have find the preprocess in the code.Thanks!

**Comment by yongqyu** [comment]
Sorry for the late reply.
If you have any other questions, please contact me.
Thank you for your interest.

2018년 12월 19일 (수) 오후 8:18, 王涛 <notifications@github.com>님이 작성:
