### ISSUE TITLE
IndexError: too many indices for array--About "0. Preprocessing"

### ISSUE THREAD

**Issue by njulug** [yongqyu/STRNN#8]
Could you help me? Thank you very much!!!!

After having Gowallat ../dataset/.
then
$ python preprocess.py
I got error like this:IndexError: too many indices for array

python ./preprocess.py
Loading data...
User/Location: 42242/1164559
==================================================================================
Making train file...
train:   0%|                                                                                            | 0/42241 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "./preprocess.py", line 148, in <module>
    run(train_user[j], batch_time, batch_lati, batch_longi, batch_loc, step=1)
  File "./preprocess.py", line 137, in run
    rnn_output = strnn_model(user, time, lati, longi, loc, step)#, neg_lati, neg_longi, neg_loc, step)
  File "/home/swim/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "./preprocess.py", line 126, in forward
    pos_h = self.return_h_tw(times, latis, longis, locs, len(times)-1)
  File "./preprocess.py", line 89, in return_h_tw
    self.return_h_tw(times, latis, longis, locs, w_cap)
  File "./preprocess.py", line 89, in return_h_tw
    self.return_h_tw(times, latis, longis, locs, w_cap)
  File "./preprocess.py", line 89, in return_h_tw
    self.return_h_tw(times, latis, longis, locs, w_cap)
  [Previous line repeated 136 more times]
  File "./preprocess.py", line 100, in return_h_tw
    data = ','.join(str(e.data.cpu().numpy()[0]) for e in locs[w_cap:idx])+"\t"
  File "./preprocess.py", line 100, in <genexpr>
    data = ','.join(str(e.data.cpu().numpy()[0]) for e in locs[w_cap:idx])+"\t"
IndexError: too many indices for array

**Comment by DongZheng0030** [comment]
I think you can change
"data = ','.join(str(e.data.cpu().numpy()[0]) for e in locs[w_cap:idx])+"\t""in preprocess.py to
"data = ','.join(str(e.data.cpu().numpy()) for e in locs[w_cap:idx]) + "\t"".
and change the "data = str(locs[idx].data.cpu().numpy()[0])+"\n"" in preprocess.py to
"data = str(locs[idx].data.cpu().numpy()) + "\n""

I hope this will help you.

**Comment by njulug** [comment]
It works!!!
Thank you very much !!!
