### ISSUE TITLE
Question about the performance

### ISSUE THREAD

**Issue by TheodoreZhao** [yongqyu/STRNN#9]
Hi Yonggyu Park,

I notice that this code is the baseline of your paper [Content-Aware Hierarchical Point-of-Interest Embedding Model for Successive POI Recommendation](https://www.ijcai.org/proceedings/2018/0458.pdf). It looks you have got a rather good performance for st-rnn that recall@1 is 0.1054. So I wonder if you have any idea about tuning the parameters on Gowalla datasets because this recall performance is largely lower than the original paper and your paper.

Thanks!

Theo

**Comment by yongqyu** [comment]
Hi Theo,

First of all, thank you for your interest in our research.
We wanted to restore the strnn as a baseline in our research but failed to re-implement it.
The difficulty of re-implementation seemed to arise from spatial interpolation.
We contacted the authors, but we could not get a clear answer.
Sorry I can not give you a helpful answer.

Thanks.

**Comment by denniszjw** [comment]
Hi Theodore , yongqyu 

I got the same performance result with @TheodoreZhao , and  through comparation of the implementation of @yongqyu and the paper , I think there is something different.

1.There is only one upper and lower bound parameter matrix , but the paper imply that every bound parameter matrix of segment is learnt.

2.What can we predict for a future trajectory by the earlier trajectories trained model  if we define an absolute start time and an end time(one upper and lower bound) ?I think there should be a periodic design of the STRNN model，which is the key point of rnn model.

Welcome to discuss.

**Comment by yongqyu** [comment]
Hi denniszjw.
Combined with two issues, the implementation of the part that looks like STRNN's key-point was hard on me. So we implemented it now for the convenience of implementation.
Because I have reading and implementing the paper long time ago, I am sorry that I can not give a specific answer.
Thank you.
